@HomeInventory.api_HostAddress = http://localhost:5196

GET {{HomeInventory.api_HostAddress}}/hi
Accept: application/json
authorization: Bearer  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRUdHlqNkdkaUxlMFVZV2l2Y3lfWiJ9.eyJuaWNrbmFtZSI6ImEiLCJuYW1lIjoiYUBhLmFhIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyL2Q5Mzg1ZDdkZWI5NTFjMDAwYTcyZTBiZTk4ZGMxMTA5P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGYS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNS0wOC0xM1QxNzowNzozNi40NDdaIiwiaXNzIjoiaHR0cHM6Ly9kZXYtaWFhbjZrYnB3Y2poazRtZS51cy5hdXRoMC5jb20vIiwiYXVkIjoiTjJjTDJaY2lqTlBia0FpRmdQMktDTkpkQWU0VE02OHAiLCJzdWIiOiJhdXRoMHw2ODhjZDI3ZmFiMzBkNjU4YjA4NjE1NGIiLCJpYXQiOjE3NTUxMDQ4NTcsImV4cCI6MTc1NTE0MDg1Nywic2lkIjoicDItS3NBcmtQLVJGUnNHQzB2ZWhwdkdkeml3WWxkVGQifQ.lS-hTKPjuFILWGasjon1q-phfCTVhSgOGjvBGSt9yA1RdBPzXO-vaCuMLqXomwFSVbRhWd_y4N6H3VLvc3XQl0QU-uSgnz0C8xvIYXK9021x_Dx-ocmKKxtV8-YnguywGOgQa4obdOnyJhxYV6-_maiH51wwDeDRa2o-A05QVxcVjmdFnrPScos2dpoN1OoNrzdr0L-MUieNDHCdnuFEiaZ63bumHbomo7-5jlHarWZXb4idS7KsY2CmFuRo-ujNm0x2OrKCz4YJug8yQn7i9tqIPdVk8lXSApRXJAR8ybNZIIlaXoySSs-ST3745GAYfzrIVKMshU46fSXp1hDEJQ

# authorization: Bearer  eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtaWFhbjZrYnB3Y2poazRtZS51cy5hdXRoMC5jb20vIn0..ZLduPmB-AG3GPwg6.N53v49wLnh62skaWuFIZzp_Rfh1KKxrErVSyjrgmgoE6r4IQL5O7c2amp_p7d9G7ERg80V7o3xksk_hn37Bw_1HYNl98PxkcseLWGZ24I4__PldOODBJ-Yjn0jImR4WlU8p9fHH3NOU8ScweSLReDtuGgNLZKdhII6xN5Mqh99dJMC3GrSQJHpUFrl0XeaLqOOyfelwc7Z1u3iq4P9-lTwy2sE1iKWidpWLe9I9xYPbacGN-QEgm3lcg7j5-M0TJkb6QRNvDCTCBqd6Im8hR7SUB_hgGgQXLb8-5xbsYpv9ItxsbYWx60EuuOVVfDbyVcaF4YQD3l3KnyeaT.ENB9wKSk8gGch1tPZUrBJA


###

GET {{HomeInventory.api_HostAddress}}/api/InventoryMembers/users/47c5699a-1541-4137-9ca6-7be07a91435a 


###

POST {{HomeInventory.api_HostAddress}}/api/Inventory/bulk/get
Content-Type: application/json

["00c82d53-a807-4607-acee-3542a82b13f4", "adac4a1f-a38d-41cd-b5c0-1278e981fc96"]
