@HomeInventory.api_HostAddress = http://localhost:5196

GET {{HomeInventory.api_HostAddress}}/hi
Accept: application/json
authorization: Bearer  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRUdHlqNkdkaUxlMFVZV2l2Y3lfWiJ9.eyJpc3MiOiJodHRwczovL2Rldi1pYWFuNmticHdjamhrNG1lLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3bWN2dXpreWg1cW9ob3RadEFIMDhHclROZHRORGQ0ZUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMyIsImlhdCI6MTc1NTAwMjkyNywiZXhwIjoxNzU1MDg5MzI3LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ3bWN2dXpreWg1cW9ob3RadEFIMDhHclROZHRORGQ0ZSJ9.gyuw1bj9fdcO4k_GoM7zH2Nzc8ZeGlWdMIjDQjNKGk-0WXcq5UXfs-t4TxD_SUPqrllxe4kra-608LRr5RcKZJ6R3NLP8WV08ACysailG8zqznZAET6djOYmnlZKayJ3fi3F10Fv_sij1ApNXeXIKLasUyCXvmw3dmVzZdGzTO2qDiTQCmcsOjcRbtpaiGtCM40axbxirNXezUws2Nkv-cJ7Rgsc0rccJGG8nc_wQvPpiB2YIOIeJm5ATFGfF52xe8bACxjzk2v7pfqpD6ZMy8fWX1XPsHAsuEfRTnMYOJY3H5ROszV77dOJwnt6Y-AOMv9bqY1xuCLrb7v-4Ewu5g


###

