// <auto-generated />
using System;
using HomeInventory.api.dbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInventory.api.Migrations
{
    [DbContext(typeof(HomeInventoryapiContext))]
    [Migration("20250810193629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HomeInventory.api.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Onwer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("HomeInventory.api.Models.InventoryMembers", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "InventoryId");

                    b.ToTable("InventoryMembers");
                });

            modelBuilder.Entity("HomeInventory.api.Models.InventoryProducts", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DesiredAmont")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExistingAmont")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId", "ProductName");

                    b.ToTable("InventoryProducts");
                });

            modelBuilder.Entity("HomeInventory.api.Models.Product", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupposedPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
